version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: dal-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rahasia123
      POSTGRES_DB: dal_fds_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
