# ==============================================================
# DAL-FDS Core Gateway Configuration
# ==============================================================

# Server Port (Vaadin UI & Java API)
server.port=8080

# --------------------------------------------------------------
# PostgreSQL Database Configuration (Docker)
# --------------------------------------------------------------
spring.datasource.url=jdbc:postgresql://localhost:5433/dal_fds_db
spring.datasource.username=postgres
spring.datasource.password=rahasia123
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA Settings (Otomatis membuat tabel jika belum ada)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --------------------------------------------------------------
# DAL Python Engine Endpoint (Microservice Communication)
# --------------------------------------------------------------
dal.engine.url=http://127.0.0.1:8000/api/v1/analyze

# --------------------------------------------------------------
# ANTI-DOS & SESSION MANAGEMENT (VAADIN)
# --------------------------------------------------------------
# 1. Bunuh sesi jika tidak ada aktivitas dalam 5 menit (mencegah RAM penuh)
server.servlet.session.timeout=5m

# 2. Paksa Vaadin untuk segera menutup UI yang sesinya sudah mati
vaadin.closeIdleSessions=true

# 3. Interval detak jantung (heartbeat) untuk mengecek apakah browser masih hidup (detik)
vaadin.heartbeatInterval=120
